export const ROUTER_APP_PATHS = {
    ROOT: "/",
    LOGIN: "/login",
    ACTIVITIES: "/activities",
    ACTIVITY: "/activities/:id",
    RESERVATION: "/reservation",
    RESERVATIONSTATE: "/reservation/:id",
    INFRASTRUCTURES: "/infrastructures",
    MORE: "/more",
    DOCUMENTS: "/documents",
    CONFIGURATION: "/configuration",
    RESERVATIONIST: "/configuration/reservations",
    RESERVATIONREVIEW: "/configuration/reservations/:id",
    ACTIVITIESLIST: "/configuration/activities",
    ACTIVITIESVIEW: "/configuration/activities/:id",
    ACTIVITIESCREATE: "/configuration/activities/create",
    INFRASTRUCTURESLIST: "/configuration/infrastructures",
    INFRASTRUCTURESVIEW: "/configuration/infrastructures/:id",
    INFRASTRUCTURESCREATE: "/configuration/infrastructures/create",
    DOCUMENTSLIST: "/configuration/documents",
    DOCUMENTSADD: "/configuration/documents/add",
};

